name: news_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Business Logic
  flutter_bloc: 

  #Comparing dart objects
  equatable:

  #Dependency Injection
  get_it: 

  #dateFormat
  intl: 

  #Database
  floor: 

  #Http
  retrofit: 

  #Hooks
  flutter_hooks:

  #Cached image
  cached_network_image: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: 
  floor_generator: 
  build_runner: 

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300

  # assets:
  #   - images/a_dot_burr.jpeg

